# Generated by Django 5.2.5 on 2025-09-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examterm',
            unique_together={('class_obj', 'name')},
        ),
        migrations.AddField(
            model_name='examterm',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='classes.class'),
        ),
        migrations.RemoveField(
            model_name='examterm',
            name='school',
        ),
    ]
