# Generated by Django 5.2.5 on 2025-09-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_examterm_unique_together_examterm_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examterm',
            options={'verbose_name': 'Exam Term', 'verbose_name_plural': 'Exam Terms'},
        ),
    ]
