# Generated by Django 5.2.5 on 2025-09-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_examterm_options'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examterm',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='examterm',
            unique_together={('school', 'name')},
        ),
        migrations.AddField(
            model_name='examterm',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='school.school'),
        ),
        migrations.RemoveField(
            model_name='examterm',
            name='class_obj',
        ),
    ]
