# Generated by Django 5.2.5 on 2025-09-23 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_examterm_options_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examterm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examterm',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='school.school'),
            preserve_default=False,
        ),
    ]
