# Generated by Django 5.2.5 on 2025-09-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
        ('exam', '0004_alter_examterm_options_and_more'),
        ('section', '0007_alter_section_unique_together_section_class_obj_and_more'),
        ('students', '0001_initial'),
        ('subject', '0003_subject_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_term',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_obj', 'section', 'roll_no']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exam.examterm'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('class_obj', 'section', 'roll_no', 'term')},
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('student_marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='students.studentmarks')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'unique_together': {('student_marks', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
