# Generated by Django 5.2.5 on 2025-09-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
