# Generated by Django 5.2.5 on 2025-09-23 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
        ('exam', '0005_examterm_created_at_alter_examterm_school'),
        ('school', '0001_initial'),
        ('section', '0007_alter_section_unique_together_section_class_obj_and_more'),
        ('students', '0003_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectmarks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentsubjectmarks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubjectmarks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examterm'),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'class_obj', 'section', 'term', 'roll_no')},
        ),
    ]
