# Generated by Django 5.2.5 on 2025-09-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
        ('exam', '0005_examterm_created_at_alter_examterm_school'),
        ('school', '0001_initial'),
        ('section', '0007_alter_section_unique_together_section_class_obj_and_more'),
        ('students', '0004_alter_student_options_and_more'),
        ('subject', '0003_subject_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_obj', 'section', 'roll_no']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectmarks',
            unique_together={('student_marks', 'subject')},
        ),
        migrations.AlterField(
            model_name='student',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='section.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exam.examterm'),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='studentsubjectmarks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentsubjectmarks',
            name='updated_at',
        ),
    ]
