# Generated by Django 5.2.5 on 2025-09-24 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
        ('exam', '0005_examterm_created_at_alter_examterm_school'),
        ('school', '0001_initial'),
        ('section', '0007_alter_section_unique_together_section_class_obj_and_more'),
        ('students', '0005_alter_student_options_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'class_obj', 'section', 'roll_no')},
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exam.examterm'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='term',
        ),
    ]
