# Generated by Django 5.0.1 on 2025-09-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('section', '0002_remove_section_class_obj_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='section.section'),
        ),
    ]
