# Generated by Django 5.0.1 on 2025-09-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_section'),
        ('section', '0004_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='section.section'),
        ),
    ]
