# Generated by Django 5.2.5 on 2025-09-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_section'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'grade')},
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
    ]
