# Generated by Django 5.2.5 on 2025-09-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['grade']},
        ),
    ]
