# Generated by Django 5.0.1 on 2025-09-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='class_obj',
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('None', 'None')], max_length=50),
        ),
    ]
