# Generated by Django 5.0.1 on 2025-09-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_remove_section_class_obj_alter_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
    ]
