# Generated by Django 5.0.1 on 2025-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_remove_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
