# Generated by Django 5.2.5 on 2025-09-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('section', '0004_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.school'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'school')},
        ),
    ]
