# Generated by Django 5.0.1 on 2025-09-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('section', '0005_section_school_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school.school'),
        ),
    ]
