# Generated by Django 5.2.5 on 2025-09-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_unique_together_remove_class_section'),
        ('section', '0006_alter_section_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.class'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'class_obj')},
        ),
    ]
